# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Robotic Perception and Learning (RPL) Seminar"
email: "d.kanoulas@ucl.ac.uk"
description: "A technical robotic seminar held at University College London (UCL), Department of Computer Science, Robotic Perception and Learning (RPL) Lab"
baseurl: "/rpl-seminar"
url: "http://rpl-as-ucl.github.io"

# Organizer Info
organizerName: "UCL-CS RPL Lab"
organizerAlternateName: "Dr. Dimitrios Kanoulas"
organizerDescription: "Lecturer (Assistant Professor) in Robotics and Computation at the University College London (UCL), Department of Computer Science, Autonomous System Research Group."
organizerEmail: "d.kanoulas@ucl.ac.uk"
organizerLogo: "/img/seo/D.Kanoulas.png"
organizerLink: "http://dkanou.github.io"

# Head
metaKeywords: "seminar, robotics"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
# - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/rpl-seminar/schedule/", text: "Schedule"}
 - {permalink: "/rpl-seminar/speakers/", text: "Speakers"}
bottomNavigationLinks:
 - {link: "http://", text: "Zoom Link"}
rightNavigationButtons:
 - {link: "http://", text: "Zoom Link"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Robotic Perception and Learning (RPL) Seminar"
heroButtons:
 - {link: "/schedule", text: "Schedule"}
 - {permalink: "/speakers", text: "Speakers"}

# About Block
aboutTitle: "About RPL Seminar"
aboutBlock:
 - {title: "Seminar", image: "workshop.jpg", text: "Virtual robotic seminars held on Fridays via Zoom." }

# Footer
socialLinks:
 - {link: "https://rpl-as-ucl.github.io/", icon: ""}
footerBlocks:
 -
  title: "Contacts"
  links:
   - {link: "mailto:d.kanoulas@ucl.ac.uk", text: "d.kanoulas@ucl.ac.uk"}

# Blog
#blogTitle: "Latest news"
#blogCommentsEnabled: true
#discusShortName: "devfestua"
